// Build stamp (July 21, 2026) — runs automatically before every build
// (npm "prebuild"). Writes the same id into:
//   public/version.json  — what the LIVE site says the newest build is
//   src/buildId.js       — what the RUNNING bundle believes it is
// UpdatePill compares the two and shows "New version — tap to refresh".
// This ends the stale-phone-bundle class of bug that's burned multiple
// debugging sessions.
const fs = require("fs");
const path = require("path");

const stamp = new Date().toISOString().replace(/[:.]/g, "-");
const root = path.join(__dirname, "..");

fs.writeFileSync(
  path.join(root, "public", "version.json"),
  JSON.stringify({ v: stamp }) + "\n"
);
fs.writeFileSync(
  path.join(root, "src", "buildId.js"),
  `// Auto-generated by scripts/stamp-version.js — do not edit.\n` +
    `export const BUILD_ID = "${stamp}";\n`
);
console.log("Stamped build:", stamp);
