// Web push sender (July 19, 2026).
//   GET  → { publicKey }  (VAPID public key — client needs it to subscribe;
//                          served from env so nothing is baked into builds)
//   POST → { targetUserId, title, body, url } with a Supabase JWT
//          → send to every subscription the target has; prune dead ones.
//
// v1 trust model: any signed-in user can trigger a push to any user id —
// the payloads are generated by our own client at real interaction moments
// (reaction/comment/tag/friend request). Harden later (verify friendship /
// rate-limit) before public scale.
//
// Env (Vercel): VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, SUPABASE_SERVICE_ROLE_KEY,
// REACT_APP_SUPABASE_URL (or SUPABASE_URL).
import webpush from "web-push";
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL =
  process.env.REACT_APP_SUPABASE_URL || process.env.SUPABASE_URL;

export default async function handler(req, res) {
  if (req.method === "GET") {
    return res.status(200).json({ publicKey: process.env.VAPID_PUBLIC_KEY || null });
  }
  if (req.method !== "POST") return res.status(405).json({ error: "POST only" });

  const pub = process.env.VAPID_PUBLIC_KEY;
  const priv = process.env.VAPID_PRIVATE_KEY;
  if (!pub || !priv || !SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return res.status(500).json({ error: "push not configured" });
  }

  const jwt = (req.headers.authorization || "").replace(/^Bearer\s+/i, "");
  if (!jwt) return res.status(401).json({ error: "no token" });

  const admin = createClient(SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
  const { data: userData, error: userErr } = await admin.auth.getUser(jwt);
  const actor = userData?.user;
  if (userErr || !actor) return res.status(401).json({ error: "bad token" });

  const { targetUserId, title, body, url } = req.body || {};
  if (!targetUserId || !title) {
    return res.status(400).json({ error: "targetUserId and title required" });
  }
  if (targetUserId === actor.id) return res.status(200).json({ sent: 0 });

  webpush.setVapidDetails("mailto:mark@sayi.do", pub, priv);

  const { data: subs } = await admin
    .from("push_subscriptions")
    .select("endpoint, p256dh, auth")
    .eq("user_id", targetUserId);

  let sent = 0;
  for (const s of subs || []) {
    try {
      await webpush.sendNotification(
        { endpoint: s.endpoint, keys: { p256dh: s.p256dh, auth: s.auth } },
        JSON.stringify({
          title: String(title).slice(0, 80),
          body: String(body || "").slice(0, 160),
          url: typeof url === "string" && url.startsWith("/") ? url : "/",
        })
      );
      sent++;
    } catch (e) {
      // Push service says this subscription is dead — clean it up.
      if (e.statusCode === 404 || e.statusCode === 410) {
        await admin.from("push_subscriptions").delete().eq("endpoint", s.endpoint);
      }
    }
  }
  return res.status(200).json({ sent });
}
